export const books = [
  {id:1,title:"Atomic Habits",originalPrice:299,price:39,pdf:"pdfs/atomic-habits.pdf"},
  {id:2,title:"Rich Dad Poor Dad",originalPrice:249,price:39,pdf:"pdfs/rich-dad-poor-dad.pdf"},
  {id:3,title:"Deep Work",originalPrice:279,price:39,pdf:"pdfs/deep-work.pdf"},
  {id:4,title:"The Power of Your Subconscious Mind",originalPrice:199,price:39,pdf:"pdfs/the-power-of-your-subconscious-mind.pdf"},
  {id:5,title:"Think and Grow Rich",originalPrice:199,price:39,pdf:"pdfs/think-and-grow-rich.pdf"},
  {id:6,title:"Ikigai",originalPrice:299,price:39,pdf:"pdfs/ikigai.pdf"},
  {id:7,title:"The Alchemist",originalPrice:249,price:39,pdf:"pdfs/the-alchemist.pdf"},
  {id:8,title:"You Can Win",originalPrice:199,price:39,pdf:"pdfs/you-can-win.pdf"},
  {id:9,title:"Indian Polity",originalPrice:399,price:39,pdf:"pdfs/indian-polity.pdf"},
  {id:10,title:"Indian Economy",originalPrice:349,price:39,pdf:"pdfs/indian-economy.pdf"},
  {id:11,title:"History of Modern India",originalPrice:329,price:39,pdf:"pdfs/history-of-modern-india.pdf"},
  {id:12,title:"Indian Art and Culture",originalPrice:299,price:39,pdf:"pdfs/indian-art-and-culture.pdf"},
  {id:13,title:"Geography of India",originalPrice:349,price:39,pdf:"pdfs/geography-of-india.pdf"},
  {id:14,title:"NCERT Indian History",originalPrice:499,price:39,pdf:"pdfs/ncert-indian-history.pdf"},
  {id:15,title:"NCERT Geography",originalPrice:499,price:39,pdf:"pdfs/ncert-geography.pdf"},
  {id:16,title:"Lucent General Knowledge",originalPrice:299,price:39,pdf:"pdfs/lucent-general-knowledge.pdf"},
  {id:17,title:"Quantitative Aptitude",originalPrice:349,price:39,pdf:"pdfs/quantitative-aptitude.pdf"},
  {id:18,title:"General Science for SSC",originalPrice:279,price:39,pdf:"pdfs/general-science-for-ssc.pdf"},
  {id:19,title:"Premchand Ki Kahaniyan",originalPrice:199,price:39,pdf:"pdfs/premchand-ki-kahaniyan.pdf"},
  {id:20,title:"Godan",originalPrice:249,price:39,pdf:"pdfs/godan.pdf"},
  {id:21,title:"Nirmala",originalPrice:199,price:39,pdf:"pdfs/nirmala.pdf"},
  {id:22,title:"Panchatantra Stories",originalPrice:149,price:39,pdf:"pdfs/panchatantra-stories.pdf"},
  {id:23,title:"Hitopadesh Stories",originalPrice:149,price:39,pdf:"pdfs/hitopadesh-stories.pdf"},
  {id:24,title:"Ramayana",originalPrice:399,price:39,pdf:"pdfs/ramayana.pdf"},
  {id:25,title:"Mahabharata",originalPrice:449,price:39,pdf:"pdfs/mahabharata.pdf"},
  {id:26,title:"Harry Potter 1",originalPrice:349,price:39,pdf:"pdfs/harry-potter-1.pdf"},
  {id:27,title:"Harry Potter 2",originalPrice:349,price:39,pdf:"pdfs/harry-potter-2.pdf"},
  {id:28,title:"The Hobbit",originalPrice:299,price:39,pdf:"pdfs/the-hobbit.pdf"},
  {id:29,title:"The Lord of the Rings",originalPrice:499,price:39,pdf:"pdfs/the-lord-of-the-rings.pdf"},
  {id:30,title:"The Kite Runner",originalPrice:299,price:39,pdf:"pdfs/the-kite-runner.pdf"},
  {id:31,title:"Wings of Fire",originalPrice:249,price:39,pdf:"pdfs/wings-of-fire.pdf"},
  {id:32,title:"Ignited Minds",originalPrice:199,price:39,pdf:"pdfs/ignited-minds.pdf"},
  {id:33,title:"My Experiments with Truth",originalPrice:249,price:39,pdf:"pdfs/my-experiments-with-truth.pdf"},
  {id:34,title:"The Monk Who Sold His Ferrari",originalPrice:299,price:39,pdf:"pdfs/the-monk-who-sold-his-ferrari.pdf"},
  {id:35,title:"India 2020",originalPrice:249,price:39,pdf:"pdfs/india-2020.pdf"},
  {id:36,title:"Reasoning",originalPrice:349,price:39,pdf:"pdfs/reasoning.pdf"},
  {id:37,title:"Fast Track Arithmetic",originalPrice:299,price:39,pdf:"pdfs/fast-track-arithmetic.pdf"},
  {id:38,title:"Objective General English",originalPrice:279,price:39,pdf:"pdfs/objective-general-english.pdf"},
  {id:39,title:"General Hindi",originalPrice:249,price:39,pdf:"pdfs/general-hindi.pdf"},
  {id:40,title:"Swami Vivekananda Stories",originalPrice:199,price:39,pdf:"pdfs/swami-vivekananda-stories.pdf"},
  {id:41,title:"Chanakya Neeti",originalPrice:149,price:39,pdf:"pdfs/chanakya-neeti.pdf"},
  {id:42,title:"Bhagavad Gita",originalPrice:299,price:39,pdf:"pdfs/bhagavad-gita.pdf"},
  {id:43,title:"Life Lessons from Ramayana",originalPrice:249,price:39,pdf:"pdfs/life-lessons-from-ramayana.pdf"},
  {id:44,title:"Do Epic Shit",originalPrice:299,price:39,pdf:"pdfs/do-epic-shit.pdf"},
  {id:45,title:"Psychology of Money",originalPrice:299,price:39,pdf:"pdfs/psychology-of-money.pdf"},
  {id:46,title:"Can't Hurt Me",originalPrice:349,price:39,pdf:"pdfs/cant-hurt-me.pdf"},
  {id:47,title:"Subtle Art",originalPrice:299,price:39,pdf:"pdfs/subtle-art.pdf"},
  {id:48,title:"Make Your Bed",originalPrice:199,price:39,pdf:"pdfs/make-your-bed.pdf"},
  {id:49,title:"Life's Amazing Secrets",originalPrice:249,price:39,pdf:"pdfs/lifes-amazing-secrets.pdf"},
  {id:50,title:"Think Like a Monk",originalPrice:299,price:39,pdf:"pdfs/think-like-a-monk.pdf"},
  {id:51,title:"The Secret",originalPrice:249,price:39,pdf:"pdfs/the-secret.pdf"},
  {id:52,title:"Mindset",originalPrice:299,price:39,pdf:"pdfs/mindset.pdf"}
];
